### ISSUE TITLE
HAX support

### ISSUE THREAD

**Issue by GabrielMajeri** [GabrielMajeri/vm-rs#2]
This issue tracks support for Intel's Hardware Accelerated Execution Manager.

**Note**: no official documentation exists, the implementation will have to reverse engineer QEMU's source code.

## To-do list
- [ ] Global device (`\\.\hax`)
  - [ ] Check HAX version
  - [ ] Check capabilities
- [ ] Virtual machine (`\\.\hax_vm##`)
  - [ ] Memory allocation
- [ ] Virtual CPU (`\\.\hax_vm##_vcpu##`)
  - [ ] State synchronisation

## Delayed
- [ ] Mac OS support: I do not have a Mac OS device, therefore I cannot test / implement HAX for OS X.
